services:
  us-east:
    ports:
    - 5000
    environment:
    - REGION=us-east
    - PYROSCOPE_LABELS=region:us-east
    - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040
    - RIDESHARE_LISTEN_PORT=5000
    build:
      context: .
  eu-north:
    ports:
    - 5000
    environment:
    - REGION=eu-north
    - PYROSCOPE_LABELS=region:eu-north
    - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040
    - RIDESHARE_LISTEN_PORT=5000
    build:
      context: .
      args:
        SDK_VERSION: "6.0"
  ap-south:
    ports:
    - 5000
    environment:
    - REGION=ap-south
    - PYROSCOPE_LABELS=region:ap-south
    - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040
    - RIDESHARE_LISTEN_PORT=5000
    build:
      context: .
      args:
        SDK_VERSION: "7.0"
  gb-south:
    ports:
    - 5000
    environment:
    - REGION=gb-south
    - PYROSCOPE_LABELS=region:ap-south
    - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040
    - RIDESHARE_LISTEN_PORT=5000
    build:
      context: .
      args:
        SDK_VERSION: "9.0"
  ap-south-alpine:
    ports:
    - 5000
    environment:
    - REGION=ap-south
    - PYROSCOPE_LABELS=region:ap-south-alpine
    - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040
    - RIDESHARE_LISTEN_PORT=5000
    build:
      context: .
      dockerfile: musl.Dockerfile

  alloy:
    image: grafana/alloy:latest
    command:
      - run
      - /etc/alloy/config.alloy
      - --stability.level=public-preview
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    ports:
      - "9999:9999"

  pyroscope:
    image: grafana/pyroscope:latest
    ports:
    - 4040:4040

  load-generator:
    build:
      context: .
      dockerfile: Dockerfile.load-generator
    environment:
    - PYROSCOPE_SERVER_ADDRESS=http://alloy:9999

  grafana:
    image: grafana/grafana:latest
    environment:
    - GF_INSTALL_PLUGINS=grafana-pyroscope-app
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
    - ./grafana-provisioning:/etc/grafana/provisioning
    ports:
    - 3000:3000
