# This fetches the Pyroscope .NET profiler SDK (musl/Alpine build)
FROM --platform=linux/amd64 docker.io/library/dotnet-musl AS sdk

FROM linuxserver/sonarr:latest

COPY --from=sdk /Pyroscope.Profiler.Native.so /opt/pyroscope/Pyroscope.Profiler.Native.so
COPY --from=sdk /Pyroscope.Linux.ApiWrapper.x64.so /opt/pyroscope/Pyroscope.Linux.ApiWrapper.x64.so

ENV CORECLR_ENABLE_PROFILING=1
ENV CORECLR_PROFILER={BD1A650D-AC5D-4896-B64F-D6FA25D6B26A}
ENV CORECLR_PROFILER_PATH=/opt/pyroscope/Pyroscope.Profiler.Native.so
ENV LD_PRELOAD=/opt/pyroscope/Pyroscope.Linux.ApiWrapper.x64.so

ENV PYROSCOPE_APPLICATION_NAME=sonarr
ENV PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040
ENV PYROSCOPE_LOG_LEVEL=debug
ENV PYROSCOPE_PROFILING_ENABLED=1
ENV PYROSCOPE_PROFILING_ALLOCATION_ENABLED=true
ENV PYROSCOPE_PROFILING_CONTENTION_ENABLED=true
ENV PYROSCOPE_PROFILING_EXCEPTION_ENABLED=true
ENV PYROSCOPE_PROFILING_HEAP_ENABLED=true
#ENV PYROSCOPE_INTERNAL_PROFILING_HEAP_SAMPLING_RATE=1024
